### PR TITLE
Port to Coq 8.9

### PR DESCRIPTION
**Pull request by Zimmi48**

### CODE REVIEW

**Comment by herbelin** [comment]
It is only about deprecated names in the arithmetic libraries, and about `fix` which shall expect a name, right?

Perfect to me.

Can it be tagged as 8.8 compatible at the same time?

**Comment by Zimmi48** [comment]
Right. The real fix is about fix. I haven't tested it but it should be 8.8-compatible (and probably with even earlier versions).

**Comment by Zimmi48** [comment]
For the record, I have a branch on top of this one adding CI and I can confirm that the version is this PR is compatible with Coq 8.7-8.9 and not with Coq 8.6 (but that was not changed by this PR). The README should probably be updated to reflect this.

**Comment by Zimmi48** [comment]
@herbelin You are the maintainer here. I'm not going to merge this PR myself.

**Pull request merged**
